# This is a basic workflow to help you get started with Actions

name: pull_requests_CI

on: pull_request

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.6 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -Iv pylint==2.5.3
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`

  unit_tests:

    runs-on: ubuntu-latest

    needs: lint
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.6
    - name: Run unit test (test_*py)
      run: python -m unittest discover -p test_*.py
