# This is a basic workflow to help you get started with Actions

name: pull_requests_CI

on: pull_request

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -Iv flake8==3.8.3
    - name: Lint python files with flake8
      run: |
        $(which flake8) --version    # pour se prémunir de ne pas trouver l'exécutable si non dans le PATH
        $(which flake8) --exclude=test_*.py
        $(which flake8) test_*.py

  unit_tests:

    runs-on: ubuntu-latest

    needs: lint
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.7
    - name: Run unit test (test_*py)
      run: python -m unittest discover -p test_*.py
